### ISSUE TITLE
Add browser compatibility

### ISSUE THREAD

**Issue by fs-c** [DoctorMcKay/node-stats-reporter#2]
Currently, the script (predictably) crashes when running in a browser. An end-user of one of your modules can, of course, prevent this by opting out of stats reporting, but it'd still be nice behaviour if this module detected that it's running in an environment where the statistics it wants to gather aren't available. Something like a quick `typeof window !== 'undefined' && typeof window.document !== 'undefined'` check should do the trick.

I'd be happy to submit a pull request for this.

**Comment by DoctorMcKay** [comment]
Honestly, tracking these stats hasn't been as useful to me as I thought it might be, so I think I'll just remove it from my modules and publish a no-op version.
